name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: fact
      id: fact
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: fact
        setup-command: ''
        command: "./output"
        input: '5'
        expected-output: '120'
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FACT_RESULTS: "${{steps.fact.outputs.result}}"
      with:
        runners: fact
